spring.application.name=anime-tracker

# Verbindung zur lokalen MongoDB-Instanz
spring.data.mongodb.uri=mongodb://localhost:27017/animedb
spring.data.mongodb.database=animedb

# Optional: zeigt die ausgefuehrten MongoDB-Befehle im Log (gut fuer die Demo)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
server.port=8081